export const expertProfileCopy = {
  breadcrumbHome: "خانه",
  breadcrumbExperts: "متخصصان",
  verifiedLabel: "تأیید شده",
  activeLabel: "فعال",
  shareLabel: "اشتراک‌گذاری",
  shareCopied: "پیوند کپی شد",
  shareError: "اشتراک‌گذاری انجام نشد. دوباره تلاش کنید.",
  shareRetry: "تلاش دوباره",
  contactLabel: "تماس",
  contactTitle: "تماس با متخصص",
  contactDescription: "با تماس یا پیامک مستقیم با متخصص گفتگو کنید.",
  callLabel: "تماس تلفنی",
  smsLabel: "ارسال پیامک",
  contactUnavailableTitle: "اطلاعات تماس در دسترس نیست",
  contactUnavailableDescription:
    "برای این متخصص هنوز راه تماس عمومی ثبت نشده است.",
  aboutTitle: "معرفی",
  aboutEmpty: "هنوز توضیحی برای این متخصص ثبت نشده است.",
  aboutExpand: "ادامه معرفی",
  aboutCollapse: "بستن",
  specialtiesTitle: "تخصص‌ها",
  professionalTitle: "اطلاعات حرفه‌ای",
  educationLabel: "تحصیلات",
  membershipLabel: "عضویت سازمان نظام مهندسی",
  licenseLabel: "پروانه اشتغال",
  disciplineLabel: "رشته",
  qualificationsLabel: "صلاحیت‌ها",
  experienceTitle: "سوابق حرفه‌ای",
  experienceYearsLabel: "سابقه فعالیت",
  cityLabel: "شهر",
  citiesTitle: "شهرهای ارائه خدمات",
  softwareTitle: "نرم‌افزارها",
  portfolioTitle: "نمونه‌کارها",
  portfolioEmpty: "هنوز نمونه‌کاری برای نمایش وجود ندارد.",
  portfolioOpen: "مشاهده نمونه‌کار",
  portfolioPrevious: "نمونه‌کار قبلی",
  portfolioNext: "نمونه‌کار بعدی",
  reviewsTitle: "نظرها",
  reviewsEmpty: "هنوز نظری ثبت نشده است.",
  reviewCountNoun: "نظر",
  reviewReplyLabel: "پاسخ متخصص",
  relatedTitle: "متخصصان مرتبط",
  ctaTitle: "ارتباط با متخصص",
  yearsSuffix: "سال",
  viewsLabel: "بازدید",
  ratingLabel: "امتیاز",
  developmentPreviewTitle: "نمونه نمایشی",
  developmentPreviewDescription:
    "این صفحه داده توسعه است و متخصص واقعی نیست. در محیط تولید نمایش داده نمی‌شود.",
} as const;

export const expertCardCopy = {
  profileCta: "مشاهده پروفایل",
} as const;
