export const EXPERT_REVIEWS_PAGE_SIZE = 9;

export const expertProfileCopy = {
  breadcrumbHome: "خانه",
  breadcrumbExperts: "متخصصان",
  verifiedLabel: "تأیید شده",
  activeLabel: "فعال",
  shareLabel: "اشتراک‌گذاری",
  shareCopied: "پیوند کپی شد",
  shareError: "اشتراک‌گذاری انجام نشد. دوباره تلاش کنید.",
  shareRetry: "تلاش دوباره",
  saveLabel: "ذخیره",
  saveUnavailableTitle: "ذخیره پروفایل هنوز فعال نیست",
  saveUnavailableDescription:
    "ذخیره متخصص به حساب کاربری مشتری نیاز دارد و پس از آماده شدن قرارداد حساب در دسترس قرار می‌گیرد.",
  chatLabel: "چت",
  chatUnavailableTitle: "گفتگوی درون‌برنامه‌ای هنوز فعال نیست",
  chatUnavailableDescription:
    "ارسال پیام و پیوست فایل در پروفایل عمومی پس از قرارداد گفتگو ممکن می‌شود. تا آن زمان از تماس یا پیامک استفاده کنید.",
  contactLabel: "اطلاعات تماس",
  contactTitle: "اطلاعات تماس",
  contactDescription: "با تماس یا پیامک مستقیم با متخصص گفتگو کنید.",
  contactCaution:
    "پیش از هر پرداخت یا هماهنگی، اطلاعات، سوابق و نمونه‌کارهای متخصص را بخوانید.",
  contactPlatformNote:
    "مهندس من راه ارتباطی امن با متخصصان حوزه ساختمان است؛ تماس شما مستقیم با متخصص انجام می‌شود.",
  callLabel: "تماس تلفنی",
  smsLabel: "ارسال پیامک",
  freeContactCta: "همین حالا و رایگان تماس بگیرید",
  contactUnavailableTitle: "اطلاعات تماس در دسترس نیست",
  contactUnavailableDescription:
    "برای این متخصص هنوز راه تماس عمومی ثبت نشده است.",
  aboutTitle: "معرفی",
  aboutEmpty: "هنوز توضیحی برای این متخصص ثبت نشده است.",
  aboutExpand: "ادامه معرفی",
  aboutCollapse: "بستن",
  specialtiesTitle: "تخصص‌ها",
  professionalTitle: "اطلاعات حرفه‌ای",
  educationLabel: "تحصیلات",
  membershipLabel: "عضویت سازمان نظام مهندسی",
  licenseLabel: "پروانه اشتغال",
  disciplineLabel: "رشته",
  qualificationsLabel: "صلاحیت‌ها",
  experienceTitle: "سوابق حرفه‌ای",
  experienceYearsLabel: "سابقه فعالیت",
  cityLabel: "شهر",
  citiesTitle: "شهرهای ارائه خدمات",
  softwareTitle: "نرم‌افزارها",
  certificatesTitle: "گواهی‌ها و مدارک",
  portfolioTitle: "نمونه‌کارهای انجام‌شده",
  portfolioEmpty: "هنوز نمونه‌کاری برای نمایش وجود ندارد.",
  portfolioOpen: "مشاهده نمونه‌کار",
  portfolioCountLabel: "عکس",
  portfolioViewerTitle: "تصاویر رزومه",
  portfolioPrevious: "نمونه‌کار قبلی",
  portfolioNext: "نمونه‌کار بعدی",
  reviewsTitle: "نظرها",
  reviewsIntro:
    "نظرهای سازنده به انتخاب بهتر سایر مشتریان کمک می‌کند. ثبت نظر پس از اتصال سرویس احراز هویت مشتری ممکن می‌شود.",
  reviewsEmpty: "هنوز نظری ثبت نشده است.",
  reviewCountNoun: "نظر",
  reviewReplyLabel: "پاسخ متخصص",
  reviewSubmitLabel: "ثبت نظر",
  reviewSubmitUnavailableTitle: "ثبت نظر هنوز فعال نیست",
  reviewSubmitUnavailableDescription:
    "ارسال امتیاز، برچسب و متن نظر به ورود مشتری و قرارداد ثبت نظر نیاز دارد و در این نسخه شبیه‌سازی نمی‌شود.",
  reviewPaginationLabel: "صفحه‌بندی نظرها",
  previousLabel: "قبلی",
  nextLabel: "بعدی",
  avatarPreviewLabel: "بزرگ‌نمایی تصویر پروفایل",
  relatedTitle: "متخصصان مرتبط",
  ctaTitle: "ارتباط با متخصص",
  yearsSuffix: "سال",
  viewsLabel: "بازدید",
  ratingLabel: "امتیاز",
  developmentPreviewTitle: "نمونه نمایشی",
  developmentPreviewDescription:
    "این صفحه داده توسعه است و متخصص واقعی نیست. در محیط تولید نمایش داده نمی‌شود.",
} as const;

export const expertCardCopy = {
  profileCta: "مشاهده پروفایل",
} as const;
