import { engineerPanelPaths } from "@/config/engineer-panel.config/engineer-panel.config";
import { userAccountPaths } from "@/config/user-account.config/user-account.config";
import { MOCK_MARKETPLACE_CUSTOMER_ID } from "@/lib/mock-data/service-request-mock-data";
import { type AppNotification } from "@/types/store/notification.types";

const BASE_MS = 1_700_000_200_000;

export const mockAppNotifications: readonly AppNotification[] = [
  {
    id: "user-ntf-1",
    recipientRole: "user",
    recipientId: MOCK_MARKETPLACE_CUSTOMER_ID,
    kind: "message",
    title: "پیام جدید از متخصص",
    body: "امیرحسین رستمی برای بازدید نقشه UTM پیام داده است.",
    createdAtLabel: "۱ ساعت پیش",
    createdAtMs: BASE_MS + 30,
    isRead: false,
    href: `${userAccountPaths.messages}/conv-utm-niavaran`,
  },
  {
    id: "user-ntf-2",
    recipientRole: "user",
    recipientId: MOCK_MARKETPLACE_CUSTOMER_ID,
    kind: "request",
    title: "وضعیت درخواست به‌روز شد",
    body: "درخواست نقشه UTM در حال بررسی است.",
    createdAtLabel: "۲ ساعت پیش",
    createdAtMs: BASE_MS + 20,
    isRead: false,
    href: `${userAccountPaths.requests}/req-utm-niavaran`,
  },
  {
    id: "user-ntf-3",
    recipientRole: "user",
    recipientId: MOCK_MARKETPLACE_CUSTOMER_ID,
    kind: "review",
    title: "نظر شما نمایش داده می‌شود",
    body: "نظر ثبت‌شده برای پروفایل متخصص در فهرست عمومی آمده است.",
    createdAtLabel: "ماه گذشته",
    createdAtMs: BASE_MS,
    isRead: true,
    href: `${userAccountPaths.reviews}/rev-req-closed-karaj`,
  },
  {
    id: "user-ntf-4",
    recipientRole: "user",
    recipientId: MOCK_MARKETPLACE_CUSTOMER_ID,
    kind: "account",
    title: "به‌روزرسانی حساب",
    body: "اطلاعات نمایشی حساب مشتری شما در پیشخوان در دسترس است.",
    createdAtLabel: "هفته گذشته",
    createdAtMs: BASE_MS - 5,
    isRead: true,
    href: userAccountPaths.settings,
  },
  {
    id: "ntf-1",
    recipientRole: "engineer",
    recipientId: "amirhossein-rostami",
    kind: "request",
    title: "درخواست جدید",
    body: "یک درخواست نقشه UTM برای پلاک ثبتی ثبت شده است.",
    createdAtLabel: "۲ ساعت پیش",
    createdAtMs: BASE_MS + 25,
    isRead: false,
    href: `${engineerPanelPaths.requests}/req-utm-niavaran`,
  },
  {
    id: "ntf-2",
    recipientRole: "engineer",
    recipientId: "amirhossein-rostami",
    kind: "message",
    title: "پیام جدید",
    body: "پاسخ تازه‌ای در گفت‌وگوی درخواست نیاوران دارید.",
    createdAtLabel: "۱ ساعت پیش",
    createdAtMs: BASE_MS + 35,
    isRead: false,
    href: `${engineerPanelPaths.messages}/conv-utm-niavaran`,
  },
  {
    id: "ntf-3",
    recipientRole: "engineer",
    recipientId: "amirhossein-rostami",
    kind: "review",
    title: "نظر جدید",
    body: "سارا مشتری برای برداشت محدوده باغ نظر ثبت کرده است.",
    createdAtLabel: "ماه گذشته",
    createdAtMs: BASE_MS + 5,
    isRead: true,
    href: `${engineerPanelPaths.reviews}/rev-req-closed-karaj`,
  },
  {
    id: "ntf-4",
    recipientRole: "engineer",
    recipientId: "amirhossein-rostami",
    kind: "verification",
    title: "وضعیت تأیید پروفایل",
    body: "وضعیت نمایشی پروفایل تأیید شده است.",
    createdAtLabel: "هفته گذشته",
    createdAtMs: BASE_MS - 10,
    isRead: true,
    href: engineerPanelPaths.profile,
  },
  {
    id: "ntf-5",
    recipientRole: "engineer",
    recipientId: "amirhossein-rostami",
    kind: "credential",
    title: "بررسی مدرک",
    body: "پروانه اشتغال در وضعیت انتظار بررسی نمایش داده می‌شود.",
    createdAtLabel: "هفته گذشته",
    createdAtMs: BASE_MS - 20,
    isRead: true,
    href: engineerPanelPaths.credentials,
  },
  ...Array.from({ length: 6 }, (_, index) => ({
    id: `ntf-extra-${index + 1}`,
    recipientRole: "engineer" as const,
    recipientId: "amirhossein-rostami",
    kind: "request" as const,
    title: `اعلان نمایشی ${index + 6}`,
    body: "این اعلان برای بررسی صفحه‌بندی فهرست اعلان‌ها اضافه شده است.",
    createdAtLabel: `${index + 4} روز پیش`,
    createdAtMs: BASE_MS - (index + 3) * 1000,
    isRead: true,
    href: engineerPanelPaths.requests,
  })),
];
