export const articlesCopy = {
  hubTitle: "مقالات",
  hubDescription: "مطالب خواندنی درباره خدمات ساختمانی و مسیر انتخاب متخصص.",
  hubBreadcrumb: "مقالات",
  categoryBreadcrumb: "دسته‌بندی",
  emptyTitle: "هنوز مقاله‌ای منتشر نشده است.",
  emptyDescription:
    "پس از اتصال منبع محتوا، فهرست مقالات در این صفحه نمایش داده می‌شود.",
  emptyCategoryTitle: "مقاله‌ای در این دسته نیست.",
  emptyCategoryDescription: "دسته‌های دیگر را ببینید یا به خانه برگردید.",
  homeCta: "بازگشت به خانه",
  browseCta: "مشاهده همه مقالات",
  relatedHeading: "مقالات مرتبط",
  recommendedHeading: "مقالات پیشنهادی",
  recommendedDescription:
    "بر اساس موضوع، برچسب و مقالات منتخب از همین مجموعه انتخاب شده‌اند.",
  tocHeading: "فهرست مطالب",
  faqsHeading: "پرسش‌های مقاله",
  serviceCtaPrefix: "مشاهده خدمت مرتبط",
  metadataDescription: "مقالات مهندس من درباره خدمات ساختمانی.",
  paginationLabel: "صفحه‌بندی مقالات",
  readMoreCta: "مطالعه بیشتر",
  featuredLabel: "مقاله منتخب",
  categoryFilterLabel: "فیلتر موضوع مقالات",
  allCategoriesLabel: "همه",
} as const;
