export const searchCopy = {
  title: "جستجوی خدمات و متخصصان",
  description: "عبارت موردنظر را وارد کنید تا خدمات مرتبط را ببینید.",
  inputLabel: "عبارت جستجو",
  placeholder: "جستجو در خدمات و متخصصین",
  submitLabel: "جستجو",
  clearLabel: "پاک کردن عبارت",
  breadcrumb: "جستجو",
  cityLabel: "انتخاب شهر",
  cityDialogDescription:
    "انتخاب شهر برای محدود کردن جستجو به‌زودی فعال می‌شود.",
  summaryPrefix: "نتایج برای",
  servicesHeading: "نتایج خدمات",
  expertsHeading: "نتایج متخصصان",
  noQueryTitle: "برای شروع جستجو، عبارت موردنظر خود را وارد کنید.",
  noQueryDescription: "می‌توانید یکی از خدمات را هم مستقیم انتخاب کنید.",
  noResultsTitle: "نتیجه‌ای برای جستجوی شما پیدا نشد.",
  noResultsDescription: "عبارت را تغییر دهید یا یکی از خدمات را ببینید.",
  expertsUnavailable: "متخصصی برای این جستجو پیدا نشد.",
  errorTitle: "جستجو انجام نشد",
  errorDescription: "لطفاً دوباره تلاش کنید یا عبارت جستجو را تغییر دهید.",
  retryLabel: "تلاش دوباره",
  browseServices: "مشاهده خدمات",
  clearFilters: "پاک کردن فیلترها",
  overlayTitle: "جستجو",
  overlayDescription: "عبارت را وارد کنید یا یکی از خدمات را انتخاب کنید.",
  overlayServices: "خدمات",
  changeSearchLabel: "تغییر جستجو",
} as const;
