import {
  type Article,
  type ArticleCategory,
} from "@/types/store/article.types";

export const mockArticleCategories: readonly ArticleCategory[] = [
  {
    slug: "surveying",
    href: "/articles/categories/surveying",
    title: "نقشه‌برداری و سند",
    description: "راهنمای برداشت، نقشه UTM و فرایندهای مرتبط با ملک.",
  },
  {
    slug: "construction",
    href: "/articles/categories/construction",
    title: "پیمانکاری و اجرا",
    description: "نکته‌های انتخاب مجری و مدیریت اجرای ساختمان.",
  },
  {
    slug: "design",
    href: "/articles/categories/design",
    title: "طراحی و نقشه",
    description: "راهنمای طراحی معماری، سازه و فضای داخلی.",
  },
];

export const mockArticles: readonly Article[] = [
  {
    id: "art-utm-map-difference",
    slug: "utm-map-difference",
    href: "/articles/utm-map-difference",
    title: "تفاوت نقشه UTM و نقشه‌برداری سند چیست؟",
    excerpt:
      "دو خروجی نزدیک اما با کاربردهای متفاوت را پیش از سفارش درست بشناسید.",
    coverSrc: "/images/articles/surveying.jpg",
    author: "تحریریه مهندس من",
    publishedAt: "۱۴ شهریور ۱۴۰۵",
    categorySlug: "surveying",
    categoryLabel: "نقشه‌برداری و سند",
    tags: ["utm", "سند", "مختصات"],
    featured: true,
    viewCount: 164,
    toc: [
      { id: "utm", label: "نقشه UTM چیست؟" },
      { id: "deed", label: "نقشه‌برداری سند چیست؟" },
      { id: "compare", label: "مقایسه کاربردها" },
    ],
    body: "نقشه UTM موقعیت و مختصات دقیق ملک را در یک سامانه مشخص ثبت می‌کند. این خروجی در جانمایی، تطبیق موقعیت و بسیاری از پیگیری‌های ثبتی کاربرد دارد.\n\nنقشه‌برداری سند علاوه بر برداشت میدانی می‌تواند به بررسی سوابق، حدود و انطباق اطلاعات ملک با مدارک موجود نیاز داشته باشد.\n\nانتخاب خدمت درست به مسئله اصلی پرونده، مرجع درخواست‌کننده و نوع خروجی مورد نیاز وابسته است. پیش از سفارش، مدارک موجود و هدف استفاده از نقشه را با متخصص در میان بگذارید.",
    faqs: [
      {
        id: "utm-use",
        question: "نقشه UTM معمولاً برای چه کاری استفاده می‌شود؟",
        answer:
          "برای تعیین موقعیت ملک در سامانه مختصات و بسیاری از پیگیری‌های ثبتی یا جانمایی.",
      },
      {
        id: "which-map",
        question: "کدام نقشه را سفارش بدهیم؟",
        answer:
          "به مرجع درخواست‌کننده و هدف پرونده بستگی دارد. مدارک موجود را با متخصص مطرح کنید.",
      },
    ],
    relatedServiceHref: "/services/land-surveying",
    relatedServiceLabel: "نقشه‌برداری",
  },
  {
    id: "art-surveying-documents",
    slug: "surveying-documents",
    href: "/articles/surveying-documents",
    title: "مدارک لازم پیش از حضور نقشه‌بردار",
    excerpt:
      "سند، دسترسی و نقشه‌های قبلی را یک‌جا آماده کنید تا نوع برداشت روشن شود.",
    coverSrc: "/images/services/surveying.png",
    author: "تحریریه مهندس من",
    publishedAt: "۱۲ شهریور ۱۴۰۵",
    categorySlug: "surveying",
    categoryLabel: "نقشه‌برداری و سند",
    tags: ["مدارک", "برداشت"],
    body: "تصویر سند، قبوض یا نقشه‌های قبلی و توضیح مسیر دسترسی، زمان هماهنگی را کوتاه می‌کند. اگر نگهبان یا محدودیت پارک دارید، همان ابتدا بگویید.",
    relatedServiceHref: "/services/land-surveying",
    relatedServiceLabel: "نقشه‌برداری",
  },
  {
    id: "art-parcel-location",
    slug: "parcel-location-when",
    href: "/articles/parcel-location-when",
    title: "چه زمانی جانمایی پلاک ثبتی ضروری است؟",
    excerpt:
      "اختلاف حدود، پرونده ثبتی یا تطبیق سند با زمین معمولاً به جانمایی نیاز دارد.",
    author: "تحریریه مهندس من",
    publishedAt: "۱۰ شهریور ۱۴۰۵",
    categorySlug: "surveying",
    categoryLabel: "نقشه‌برداری و سند",
    tags: ["سند", "ثبت", "جانمایی"],
    body: "اگر حدود روی زمین با سند هم‌خوان نیست یا مرجع ثبتی تطبیق موقعیت خواسته، جانمایی پلاک ثبتی مسیر درست است. این کار با نقشه UTM معمولی یکی نیست.",
    relatedServiceHref: "/services/land-surveying",
    relatedServiceLabel: "نقشه‌برداری",
  },
  {
    id: "art-topo-vs-utm",
    slug: "topo-vs-utm",
    href: "/articles/topo-vs-utm",
    title: "تفاوت برداشت توپوگرافی و نقشه UTM",
    excerpt:
      "توپوگرافی شکل زمین را نشان می‌دهد؛ UTM موقعیت ملک را در سامانه مختصات ثبت می‌کند.",
    coverSrc: "/images/articles/surveying.jpg",
    author: "تحریریه مهندس من",
    publishedAt: "۸ شهریور ۱۴۰۵",
    categorySlug: "surveying",
    categoryLabel: "نقشه‌برداری و سند",
    tags: ["utm", "توپوگرافی"],
    body: "برای طراحی محوطه یا محاسبه خاک‌برداری معمولاً توپوگرافی لازم است. برای ثبت و جانمایی، خروجی UTM کاربرد دارد. هر دو را بدون نیاز واقعی سفارش ندهید.",
    relatedServiceHref: "/services/land-surveying",
    relatedServiceLabel: "نقشه‌برداری",
  },
  {
    id: "art-asbuilt-renovation",
    slug: "asbuilt-renovation",
    href: "/articles/asbuilt-renovation",
    title: "نقشه ازبیلت در پروژه بازسازی چه کمکی می‌کند؟",
    excerpt:
      "وضعیت موجود را قبل از تخریب ثبت کنید تا طراحی و اجرا روی فرض اشتباه نرود.",
    author: "تحریریه مهندس من",
    publishedAt: "۷ شهریور ۱۴۰۵",
    categorySlug: "surveying",
    categoryLabel: "نقشه‌برداری و سند",
    tags: ["ازبیلت", "بازسازی"],
    body: "ازبیلت ابعاد و تراز واقعی را نشان می‌دهد. در بازسازی، این خروجی جلوی تداخل تأسیسات و سازه را می‌گیرد و مبنای قرارداد اجرا را شفاف می‌کند.",
    relatedServiceHref: "/services/land-surveying",
    relatedServiceLabel: "نقشه‌برداری",
  },
  {
    id: "art-surveying-scope",
    slug: "surveying-scope",
    href: "/articles/surveying-scope",
    title: "چطور محدوده کار نقشه‌برداری را شفاف کنیم؟",
    excerpt:
      "مرز ملک، نقاط موردنیاز و نوع فایل تحویلی را پیش از بازدید بنویسید.",
    author: "تحریریه مهندس من",
    publishedAt: "۶ شهریور ۱۴۰۵",
    categorySlug: "surveying",
    categoryLabel: "نقشه‌برداری و سند",
    tags: ["محدوده کار", "برداشت"],
    body: "یک فهرست کوتاه از خروجی، مقیاس، فرمت فایل و نقاط خاص روی زمین از رفت‌وبرگشت بعدی جلوگیری می‌کند.",
    relatedServiceHref: "/services/land-surveying",
    relatedServiceLabel: "نقشه‌برداری",
  },
  {
    id: "art-registry-output",
    slug: "municipality-registry-output",
    href: "/articles/municipality-registry-output",
    title: "خروجی مناسب شهرداری و ثبت را چطور مشخص کنیم؟",
    excerpt:
      "نام مرجع را دقیق بپرسید؛ قالب فایل شهرداری و ثبت معمولاً یکی نیست.",
    coverSrc: "/images/services/license.png",
    author: "تحریریه مهندس من",
    publishedAt: "۵ شهریور ۱۴۰۵",
    categorySlug: "surveying",
    categoryLabel: "نقشه‌برداری و سند",
    tags: ["شهرداری", "ثبت", "utm"],
    body: "پیش از سفارش، نامه یا چک‌لیست مرجع را بخوانید. اگر نام خروجی مبهم است، همان متن را برای متخصص بفرستید.",
    relatedServiceHref: "/services/land-surveying",
    relatedServiceLabel: "نقشه‌برداری",
  },
  {
    id: "art-field-access",
    slug: "field-access-safety",
    href: "/articles/field-access-safety",
    title: "نکته‌های دسترسی و ایمنی در برداشت میدانی",
    excerpt:
      "ورود به ملک، حضور مالک و موانع اجرایی را قبل از ساعت حضور هماهنگ کنید.",
    author: "تحریریه مهندس من",
    publishedAt: "۴ شهریور ۱۴۰۵",
    categorySlug: "surveying",
    categoryLabel: "نقشه‌برداری و سند",
    tags: ["ایمنی", "برداشت"],
    body: "کارگاه فعال، سگ نگهبان یا سقف ناایمن باید از قبل اعلام شود. برداشت دقیق به دسترسی امن وابسته است.",
    relatedServiceHref: "/services/land-surveying",
    relatedServiceLabel: "نقشه‌برداری",
  },
  {
    id: "art-apartment-split",
    slug: "apartment-split-info",
    href: "/articles/apartment-split-info",
    title: "تفکیک آپارتمان؛ چه اطلاعاتی باید آماده باشد؟",
    excerpt:
      "طبقات، پارکینگ و انباری را با مدارک ثبتی هم‌خوان کنید تا صورت‌جلسه کامل شود.",
    author: "تحریریه مهندس من",
    publishedAt: "۳ شهریور ۱۴۰۵",
    categorySlug: "surveying",
    categoryLabel: "نقشه‌برداری و سند",
    tags: ["تفکیک", "سند"],
    body: "نقشه معماری موجود، تعداد واحدها و سهم مشاعات را آماده کنید. اختلاف این ارقام با وضع موجود باید قبل از تنظیم صورت‌مجلس روشن شود.",
    relatedServiceHref: "/services/land-surveying",
    relatedServiceLabel: "نقشه‌برداری",
  },
  {
    id: "art-drone-survey",
    slug: "drone-survey-when",
    href: "/articles/drone-survey-when",
    title: "برداشت پهپادی چه زمانی انتخاب درستی است؟",
    excerpt:
      "زمین وسیع یا دسترسی سخت گاهی با پهپاد سریع‌تر است؛ ملک کوچک شهری معمولاً نه.",
    coverSrc: "/images/portfolio/project-01.jpg",
    author: "تحریریه مهندس من",
    publishedAt: "۲ شهریور ۱۴۰۵",
    categorySlug: "surveying",
    categoryLabel: "نقشه‌برداری و سند",
    tags: ["پهپاد", "توپوگرافی"],
    body: "محدودیت پرواز شهری، پوشش گیاهی و دقت موردنیاز را با متخصص بررسی کنید. پهپاد جایگزین همه برداشت‌های زمینی نیست.",
    relatedServiceHref: "/services/land-surveying",
    relatedServiceLabel: "نقشه‌برداری",
  },
  {
    id: "art-after-map-delivery",
    slug: "after-map-delivery",
    href: "/articles/after-map-delivery",
    title: "پس از تحویل نقشه، چه بررسی‌هایی باقی می‌ماند؟",
    excerpt:
      "مقیاس، سیستم مختصات و انطباق با سند را قبل از ارسال به مرجع کنترل کنید.",
    author: "تحریریه مهندس من",
    publishedAt: "۱ شهریور ۱۴۰۵",
    categorySlug: "surveying",
    categoryLabel: "نقشه‌برداری و سند",
    tags: ["تحویل", "utm"],
    body: "فایل را روی رایانه خود باز کنید، نام لایه‌ها و مهر یا امضای موردنیاز را بسنجید و یک نسخه پشتیبان نگه دارید.",
    relatedServiceHref: "/services/land-surveying",
    relatedServiceLabel: "نقشه‌برداری",
  },
  {
    id: "art-contractor-selection",
    slug: "contractor-selection",
    href: "/articles/contractor-selection",
    title: "پیش از انتخاب پیمانکار ساختمان چه چیزهایی را بررسی کنیم؟",
    excerpt: "یک چک‌لیست کوتاه برای مقایسه سابقه، محدوده کار و شیوه همکاری.",
    coverSrc: "/images/services/contractor.png",
    author: "تحریریه مهندس من",
    publishedAt: "۹ شهریور ۱۴۰۵",
    categorySlug: "construction",
    categoryLabel: "پیمانکاری و اجرا",
    tags: ["پیمانکار", "قرارداد"],
    featured: true,
    viewCount: 91,
    body: "نمونه‌کارهای مشابه، تعریف روشن محدوده کار، برنامه زمانی و شیوه گزارش‌دهی چهار نقطه شروع مهم هستند. گفت‌وگوی اولیه باید به پرسش‌های مشخص درباره مسئولیت‌ها و تحویل هر مرحله پاسخ دهد.",
    relatedServiceHref: "/services/construction-workers",
    relatedServiceLabel: "استادکار و پیمانکار",
  },
  {
    id: "art-construction-contract",
    slug: "construction-contract-scope",
    href: "/articles/construction-contract-scope",
    title: "محدوده کار را چطور در قرارداد اجرا بنویسیم؟",
    excerpt:
      "مصالح، نیروی کار و کارهای خارج از قرارداد را جدا کنید تا اختلاف بعدی کم شود.",
    author: "تحریریه مهندس من",
    publishedAt: "۱۱ شهریور ۱۴۰۵",
    categorySlug: "construction",
    categoryLabel: "پیمانکاری و اجرا",
    tags: ["قرارداد", "محدوده کار"],
    body: "فهرست کارهای مشمول، استثناها و نحوه تأیید تغییر کار را بنویسید. ابهام در همین بندها بیشترین توقف کارگاه را می‌سازد.",
    relatedServiceHref: "/services/construction-workers",
    relatedServiceLabel: "استادکار و پیمانکار",
  },
  {
    id: "art-weekly-site-report",
    slug: "weekly-site-report",
    href: "/articles/weekly-site-report",
    title: "گزارش هفتگی کارگاه باید چه چیزهایی داشته باشد؟",
    excerpt:
      "پیشرفت، تأخیر، نیروی حاضر و تصمیم‌های باز را در یک صفحه خلاصه کنید.",
    coverSrc: "/images/home/hero-construction.png",
    author: "تحریریه مهندس من",
    publishedAt: "۱۳ شهریور ۱۴۰۵",
    categorySlug: "construction",
    categoryLabel: "پیمانکاری و اجرا",
    tags: ["کارگاه", "گزارش"],
    body: "گزارش خوب عکس وضعیت، درصد پیشرفت نسبت به برنامه و درخواست‌های تأییدنشده را نشان می‌دهد. پیام‌های پراکنده در پیام‌رسان جایگزین آن نیست.",
    relatedServiceHref: "/services/construction-workers",
    relatedServiceLabel: "استادکار و پیمانکار",
  },
  {
    id: "art-material-delivery",
    slug: "material-delivery-check",
    href: "/articles/material-delivery-check",
    title: "تحویل مصالح را چطور در کارگاه کنترل کنیم؟",
    excerpt:
      "مقدار، کیفیت ظاهری و محل دپو را همان روز ورود ثبت کنید نه بعد از مصرف.",
    author: "تحریریه مهندس من",
    publishedAt: "۱۵ شهریور ۱۴۰۵",
    categorySlug: "construction",
    categoryLabel: "پیمانکاری و اجرا",
    tags: ["مصالح", "کارگاه"],
    body: "برگه وزن یا تعداد، عکس بسته‌بندی و نام تحویل‌گیرنده را نگه دارید. اختلاف مصالح معمولاً وقتی پیدا می‌شود که دیگر قابل برگشت نیست.",
    relatedServiceHref: "/services/construction-workers",
    relatedServiceLabel: "استادکار و پیمانکار",
  },
  {
    id: "art-crew-size",
    slug: "crew-size-small-project",
    href: "/articles/crew-size-small-project",
    title: "اندازه تیم اجرا برای پروژه کوچک را چطور بسنجیم؟",
    excerpt:
      "تیم بزرگ روی واحد کوچک لزوماً سریع‌تر نیست و گاهی هماهنگی را سخت می‌کند.",
    author: "تحریریه مهندس من",
    publishedAt: "۱۶ شهریور ۱۴۰۵",
    categorySlug: "construction",
    categoryLabel: "پیمانکاری و اجرا",
    tags: ["اجرا", "برنامه"],
    body: "فضای کار، تداخل رشته‌ها و ساعات مجاز صدا را در نظر بگیرید. پیمانکار باید ترکیب نیرو را با برنامه واقعی توضیح دهد.",
    relatedServiceHref: "/services/construction-workers",
    relatedServiceLabel: "استادکار و پیمانکار",
  },
  {
    id: "art-schedule-buffer",
    slug: "construction-schedule-buffer",
    href: "/articles/construction-schedule-buffer",
    title: "چرا برنامه اجرا بدون ذخیره زمانی شکست می‌خورد؟",
    excerpt:
      "تأمین مصالح، مجوز و هوای نامساعد را در زمان‌بندی ببینید نه بعد از تأخیر.",
    coverSrc: "/images/home/project-engineer.png",
    author: "تحریریه مهندس من",
    publishedAt: "۱۷ شهریور ۱۴۰۵",
    categorySlug: "construction",
    categoryLabel: "پیمانکاری و اجرا",
    tags: ["برنامه", "تأخیر"],
    body: "یک ذخیره کوتاه برای خرید، خشک‌شدن مصالح و بازدید ناظر واقع‌بینانه‌تر از تاریخ فشرده تبلیغاتی است.",
    relatedServiceHref: "/services/construction-workers",
    relatedServiceLabel: "استادکار و پیمانکار",
  },
  {
    id: "art-project-handover",
    slug: "project-handover-checklist",
    href: "/articles/project-handover-checklist",
    title: "چک‌لیست تحویل پروژه ساختمانی",
    excerpt:
      "نواقص، گارانتی و مدارک نقشه‌های چون‌ساخت را قبل از تسویه نهایی ببندید.",
    author: "تحریریه مهندس من",
    publishedAt: "۱۸ شهریور ۱۴۰۵",
    categorySlug: "construction",
    categoryLabel: "پیمانکاری و اجرا",
    tags: ["تحویل", "قرارداد"],
    body: "صورت‌جلسه تحویل، فهرست نقص و زمان رفع آن را مکتوب کنید. تسویه کامل پیش از رفع موارد ایمنی توصیه نمی‌شود.",
    relatedServiceHref: "/services/construction-workers",
    relatedServiceLabel: "استادکار و پیمانکار",
  },
  {
    id: "art-interior-design-brief",
    slug: "interior-design-brief",
    href: "/articles/interior-design-brief",
    title: "چطور برای طراحی داخلی یک شرح نیاز خوب آماده کنیم؟",
    excerpt:
      "نیازهای فضایی، بودجه و سلیقه را به زبان قابل استفاده برای طراح تبدیل کنید.",
    coverSrc: "/images/home/interior-design.png",
    author: "تحریریه مهندس من",
    publishedAt: "۳ شهریور ۱۴۰۵",
    categorySlug: "design",
    categoryLabel: "طراحی و نقشه",
    tags: ["داخلی", "شرح نیاز"],
    featured: true,
    viewCount: 72,
    body: "فهرست کاربران فضا، فعالیت‌های روزانه، محدودیت بودجه و نمونه‌هایی که دوست دارید یا نمی‌پسندید را ثبت کنید. یک شرح نیاز خوب تصمیم‌ها را سریع‌تر و نتیجه را قابل ارزیابی‌تر می‌کند.",
    relatedServiceHref: "/services/interior-design",
    relatedServiceLabel: "طراحی نما و داخلی",
  },
  {
    id: "art-read-architecture-plan",
    slug: "how-to-read-architecture-plan",
    href: "/articles/how-to-read-architecture-plan",
    title: "چطور پلان معماری را قبل از اجرا بخوانیم؟",
    excerpt:
      "ابعاد، جهت شمال، مبلمان و علائم در و پنجره را روی همان برگه پیدا کنید.",
    coverSrc: "/images/services/designer.png",
    author: "تحریریه مهندس من",
    publishedAt: "۱۹ شهریور ۱۴۰۵",
    categorySlug: "design",
    categoryLabel: "طراحی و نقشه",
    tags: ["پلان", "معماری"],
    body: "مقیاس را چک کنید، مسیر گردش را دنبال کنید و فضاهایی که روی پلان تنگ به نظر می‌رسند را با ابعاد واقعی بسنجید. پرسش‌ها را قبل از بتن‌ریزی بپرسید.",
    relatedServiceHref: "/services/drawing",
    relatedServiceLabel: "ترسیم نقشه",
  },
  {
    id: "art-facade-material",
    slug: "facade-material-choice",
    href: "/articles/facade-material-choice",
    title: "انتخاب متریال نما؛ دوام را فدای عکس نکنید",
    excerpt: "اقلیم، نگهداری و جزئیات اتصال را کنار رنگ و بافت ببینید.",
    author: "تحریریه مهندس من",
    publishedAt: "۲۰ شهریور ۱۴۰۵",
    categorySlug: "design",
    categoryLabel: "طراحی و نقشه",
    tags: ["نما", "متریال"],
    body: "نمونه واقعی را در نور روز ببینید و از مجری جزئیات درز و زیرسازی را بخواهید. نمای زیبا بدون جزئیات اجرایی خیلی زود لکه یا ترک برمی‌دارد.",
    relatedServiceHref: "/services/interior-design",
    relatedServiceLabel: "طراحی نما و داخلی",
  },
  {
    id: "art-lighting-layers",
    slug: "interior-lighting-layers",
    href: "/articles/interior-lighting-layers",
    title: "لایه‌های نور در فضای داخلی چه کمکی می‌کنند؟",
    excerpt:
      "نور عمومی، موضعی و تأکیدی را جدا کنید تا فضا هم کار کند هم خسته نکند.",
    author: "تحریریه مهندس من",
    publishedAt: "۲۱ شهریور ۱۴۰۵",
    categorySlug: "design",
    categoryLabel: "طراحی و نقشه",
    tags: ["داخلی", "نور"],
    body: "قبل از خرید لوستر، محل کار، مسیر حرکت و نقاط نمایش را مشخص کنید. سیم‌کشی دیرتر از نازک‌کاری گران تمام می‌شود.",
    relatedServiceHref: "/services/interior-design",
    relatedServiceLabel: "طراحی نما و داخلی",
  },
  {
    id: "art-kitchen-layout",
    slug: "kitchen-layout-mistakes",
    href: "/articles/kitchen-layout-mistakes",
    title: "اشتباه‌های رایج در چیدمان آشپزخانه",
    excerpt:
      "مثلث کار، عرض مسیر و جای سطل زباله را قبل از سفارش کابینت ببندید.",
    coverSrc: "/images/portfolio/project-02.jpg",
    author: "تحریریه مهندس من",
    publishedAt: "۲۲ شهریور ۱۴۰۵",
    categorySlug: "design",
    categoryLabel: "طراحی و نقشه",
    tags: ["داخلی", "آشپزخانه"],
    body: "درب یخچال و ماشین لباسشویی نباید مسیر را ببندد. اندازه‌گیری بعد از نازک‌کاری دقیق‌تر از عدد روی پلان اولیه است.",
    relatedServiceHref: "/services/interior-design",
    relatedServiceLabel: "طراحی نما و داخلی",
  },
  {
    id: "art-arch-structure-coord",
    slug: "architecture-structure-coordination",
    href: "/articles/architecture-structure-coordination",
    title: "هماهنگی معماری و سازه را از کجا شروع کنیم؟",
    excerpt: "محل ستون، داکت و سقف کاذب را روی یک جلسه مشترک قفل کنید.",
    author: "تحریریه مهندس من",
    publishedAt: "۲۳ شهریور ۱۴۰۵",
    categorySlug: "design",
    categoryLabel: "طراحی و نقشه",
    tags: ["پلان", "سازه"],
    body: "تغییر دیرهنگام دهانه یا محل داکت گران است. نقشه‌های معماری و سازه را قبل از اجرا روی هم بیندازید و تعارض را مکتوب کنید.",
    relatedServiceHref: "/services/drawing",
    relatedServiceLabel: "ترسیم نقشه",
  },
  {
    id: "art-drawings-for-permit",
    slug: "drawings-for-permit",
    href: "/articles/drawings-for-permit",
    title: "چه نقشه‌هایی معمولاً برای پروانه ساخت لازم است؟",
    excerpt: "معماری، سازه و تأسیسات را با چک‌لیست همان شهرداری تطبیق دهید.",
    coverSrc: "/images/services/licence.png",
    author: "تحریریه مهندس من",
    publishedAt: "۲۴ شهریور ۱۴۰۵",
    categorySlug: "design",
    categoryLabel: "طراحی و نقشه",
    tags: ["پروانه", "نقشه"],
    body: "فهرست مدارک شهر به شهر فرق دارد. از طراح بخواهید شیت‌ها را با همان قالب مرجع آماده کند تا اصلاحیه کمتری بخورید.",
    relatedServiceHref: "/services/building-permit",
    relatedServiceLabel: "پروانه ساخت",
  },
];
